export interface Photo {
  id: string;
  title: string;
  category: 'nature' | 'cars';
  imagePath: string;
  price: number;
  dimensions?: string;
  description?: string;
  orientation: 'horizontal' | 'vertical' | 'square';
  available: boolean;
}

export const photos: Photo[] = [
  {
    id: '1',
    title: 'DJI 0149',
    category: 'nature',
    imagePath: '/photography/DJI_0149.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '2',
    title: 'DJI 0231',
    category: 'nature',
    imagePath: '/photography/DJI_0231.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '3',
    title: 'IMG 0480',
    category: 'nature',
    imagePath: '/photography/IMG_0480.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '4',
    title: 'IMG 0953',
    category: 'nature',
    imagePath: '/photography/IMG_0953.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '5',
    title: 'IMG 2145',
    category: 'nature',
    imagePath: '/photography/IMG_2145.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '6',
    title: 'IMG 2207',
    category: 'nature',
    imagePath: '/photography/IMG_2207.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '7',
    title: 'IMG 2610',
    category: 'nature',
    imagePath: '/photography/IMG_2610.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '8',
    title: 'IMG 2684',
    category: 'nature',
    imagePath: '/photography/IMG_2684_01.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '9',
    title: 'IMG 2835',
    category: 'nature',
    imagePath: '/photography/IMG_2835.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '10',
    title: 'R6 4498',
    category: 'nature',
    imagePath: '/photography/R6__4498_02.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '11',
    title: 'R6 4613',
    category: 'nature',
    imagePath: '/photography/R6__4613_02.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '12',
    title: 'R6 4809',
    category: 'nature',
    imagePath: '/photography/R6__4809_02.jpg',
    price: 200,
    dimensions: '20x20"',
    orientation: 'square',
    available: true,
  },
  {
    id: '13',
    title: 'R6 4811',
    category: 'nature',
    imagePath: '/photography/R6__4811_02.jpg',
    price: 200,
    dimensions: '20x20"',
    orientation: 'square',
    available: true,
  },
  {
    id: '14',
    title: 'R6 4831',
    category: 'nature',
    imagePath: '/photography/R6__4831_01.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '15',
    title: 'R6 4861',
    category: 'nature',
    imagePath: '/photography/R6__4861.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '16',
    title: 'R6 4902',
    category: 'nature',
    imagePath: '/photography/R6__4902_01.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '17',
    title: 'R6 4939',
    category: 'nature',
    imagePath: '/photography/R6__4939_01.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '18',
    title: 'R6 5175',
    category: 'nature',
    imagePath: '/photography/R6__5175_01.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '19',
    title: 'R6 5200',
    category: 'nature',
    imagePath: '/photography/R6__5200.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '20',
    title: 'R6 5225',
    category: 'nature',
    imagePath: '/photography/R6__5225.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '21',
    title: 'R6 5581',
    category: 'nature',
    imagePath: '/photography/R6__5581.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '22',
    title: 'R6 5596',
    category: 'nature',
    imagePath: '/photography/R6__5596.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '23',
    title: 'R6 5671',
    category: 'nature',
    imagePath: '/photography/R6__5671.jpg',
    price: 180,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: '24',
    title: 'R6 5676',
    category: 'nature',
    imagePath: '/photography/R6__5676.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '25',
    title: 'R6 5817',
    category: 'nature',
    imagePath: '/photography/R6__5817.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '26',
    title: 'Hurricane',
    category: 'nature',
    imagePath: '/photography/[M-Y]hurricane.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '27',
    title: 'Mini Waterfall',
    category: 'nature',
    imagePath: '/photography/[M]miniwaterLQ.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '28',
    title: 'Falls',
    category: 'nature',
    imagePath: '/photography/[Y]LQfalls.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '29',
    title: 'Crater Lake',
    category: 'nature',
    imagePath: '/photography/[Y]craterlake.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '30',
    title: 'Fog Trees',
    category: 'nature',
    imagePath: '/photography/[Y]fogtrees - Copy.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '31',
    title: 'Goat',
    category: 'nature',
    imagePath: '/photography/[Y]goat.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '32',
    title: 'Sol Duc',
    category: 'nature',
    imagePath: '/photography/[Y]solduc.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '33',
    title: 'Stars',
    category: 'nature',
    imagePath: '/photography/[Y]stars.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '34',
    title: 'Wood Path',
    category: 'nature',
    imagePath: '/photography/[Y]woodpathLQ.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '35',
    title: 'Aerial View',
    category: 'nature',
    imagePath: '/photography/dji_fly_20240525_135550_146_1716670561873_photo_optimized.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '36',
    title: 'Graduation 1',
    category: 'nature',
    imagePath: '/photography/gra5_1.2.1.jpg',
    price: 120,
    dimensions: '11x14"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '37',
    title: 'Graduation 2',
    category: 'nature',
    imagePath: '/photography/grab2_1.1.2.jpg',
    price: 120,
    dimensions: '11x14"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: '38',
    title: 'Graduation 3',
    category: 'nature',
    imagePath: '/photography/grab3_1.1.3.jpg',
    price: 120,
    dimensions: '11x14"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-1',
    title: '2L9A0555',
    category: 'cars',
    imagePath: '/photography/2L9A0555.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: 'car-2',
    title: '2L9A0558',
    category: 'cars',
    imagePath: '/photography/2L9A0558.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: 'car-3',
    title: '2L9A8756',
    category: 'cars',
    imagePath: '/photography/2L9A8756.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-4',
    title: 'IMG 1254',
    category: 'cars',
    imagePath: '/photography/IMG_1254.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-5',
    title: 'IMG 1280',
    category: 'cars',
    imagePath: '/photography/IMG_1280.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-6',
    title: 'IMG 1332',
    category: 'cars',
    imagePath: '/photography/IMG_1332.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-7',
    title: 'IMG 1340',
    category: 'cars',
    imagePath: '/photography/IMG_1340.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-8',
    title: 'IMG 1341',
    category: 'cars',
    imagePath: '/photography/IMG_1341.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-9',
    title: 'IMG 1350',
    category: 'cars',
    imagePath: '/photography/IMG_1350.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-10',
    title: 'IMG 2235 05',
    category: 'cars',
    imagePath: '/photography/IMG_2235_05.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-11',
    title: 'IMG 4199 02',
    category: 'cars',
    imagePath: '/photography/IMG_4199_02.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: 'car-12',
    title: 'IMG 4225',
    category: 'cars',
    imagePath: '/photography/IMG_4225.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-13',
    title: 'IMG 4274',
    category: 'cars',
    imagePath: '/photography/IMG_4274.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-14',
    title: 'IMG 4281',
    category: 'cars',
    imagePath: '/photography/IMG_4281.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: 'car-15',
    title: 'IMG 8562',
    category: 'cars',
    imagePath: '/photography/IMG_8562.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-16',
    title: 'IMG 8663',
    category: 'cars',
    imagePath: '/photography/IMG_8663.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-17',
    title: 'IMG 8711',
    category: 'cars',
    imagePath: '/photography/IMG_8711.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-18',
    title: 'IMG 8727',
    category: 'cars',
    imagePath: '/photography/IMG_8727.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-19',
    title: 'IMG 8734',
    category: 'cars',
    imagePath: '/photography/IMG_8734.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-20',
    title: 'IMG 8752',
    category: 'cars',
    imagePath: '/photography/IMG_8752.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-21',
    title: 'IMG 8762',
    category: 'cars',
    imagePath: '/photography/IMG_8762.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-22',
    title: 'IMG 8805',
    category: 'cars',
    imagePath: '/photography/IMG_8805.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-23',
    title: 'IMG 8806',
    category: 'cars',
    imagePath: '/photography/IMG_8806.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-24',
    title: 'IMG 8881',
    category: 'cars',
    imagePath: '/photography/IMG_8881.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-25',
    title: 'R6 5400',
    category: 'cars',
    imagePath: '/photography/R6__5400.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-26',
    title: 'R6 5424',
    category: 'cars',
    imagePath: '/photography/R6__5424.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-27',
    title: 'R6 5431',
    category: 'cars',
    imagePath: '/photography/R6__5431.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-28',
    title: 'R6 5438',
    category: 'cars',
    imagePath: '/photography/R6__5438.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-29',
    title: 'R6 5441',
    category: 'cars',
    imagePath: '/photography/R6__5441.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: 'car-30',
    title: 'R6 5518',
    category: 'cars',
    imagePath: '/photography/R6__5518.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-31',
    title: 'R6 5525',
    category: 'cars',
    imagePath: '/photography/R6__5525.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-32',
    title: 'R6 5526',
    category: 'cars',
    imagePath: '/photography/R6__5526.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'vertical',
    available: true,
  },
  {
    id: 'car-33',
    title: 'R6 5530',
    category: 'cars',
    imagePath: '/photography/R6__5530.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
  {
    id: 'car-34',
    title: 'R6 5541 01',
    category: 'cars',
    imagePath: '/photography/R6__5541_01.jpg',
    price: 150,
    dimensions: '16x20"',
    orientation: 'horizontal',
    available: true,
  },
];

export const categories = [
  { value: 'all', label: 'All' },
  { value: 'nature', label: 'Nature' },
  { value: 'cars', label: 'Cars' },
] as const;
